---
- hosts: all
  roles:

- hosts: laptops
  roles:
    - common
    - laptop
    - logwatch
    - cron
    - sendmail
    - firewalld

- hosts: vps
  roles:
    - common
    - { role: sendmail, tags: sendmail}
    - fail2ban
    - { role: logwatch, tags: logwatch }
    - firewalld
    - named-chroot
    - { role: cron, tags: cron }
    - { role: s, tags: s }

- hosts: kali
  roles:
    - common
    - kali

- hosts: axiom
  roles:
    - common
    - axiom

- hosts: proxmox
  roles:
    - common
    - proxmox

- hosts: minibook
  roles:
    - common
    - minibook

- hosts: desktops
  roles:
    - common
    - desktops
