---
- hosts: all
  roles:
  - common

- hosts: laptops
  roles:
  - laptop
  - logwatch
  - cron
  - sendmail
  - firewalld

- hosts: vps
  roles:
    - { role: sendmail, tags: sendmail}
    - fail2ban
    - { role: logwatch, tags: logwatch }
    - firewalld
    - named-chroot
    - { role: cron, tags: cron }
    - { role: s, tags: s }

- hosts: kali
  roles:
  - kali

- hosts: axiom
  roles:
  - axiom

- hosts: proxmox
  roles:
  - proxmox

- hosts: minibook
  roles:
  - minibook

- hosts: desktops
  roles:
  - desktops
