---
- name: Proxmox install packages
  become: yes
  apt: 
    update_cache: yes
    cache_valid_time: 86400 #1 day
    name:
        - nfs-kernel-server
    state: present
  when: ansible_distribution == 'Debian'

- name: Enable service ssh and start it
  ansible.builtin.service:
    name: ssh
    enabled: yes
    state: started
  when: ansible_distribution == 'Debian'
