- name: Add Vivaldi GPG key
  ansible.builtin.get_url:
    url: https://repo.vivaldi.com/archive/linux_signing_key.pub
    dest: /usr/share/keyrings/vivaldi-archive-keyring.asc
    mode: '0644'
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Add Vivaldi Repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/vivaldi-archive-keyring.asc] https://repo.vivaldi.com/archive/deb/ stable main"
    filename: vivaldi
    state: present
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Install Ubuntu packages
  become: yes
  apt: 
    update_cache: yes
    cache_valid_time: 86400 #1 day
    name:
    - python3-gpg
    - openssh-server
    - keepassxc-full
    - neovim
    - libappindicator3-1
    - calibre
    - stow
    - build-essential
    - krdc
    - vivaldi-stable
    state: present
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Ubuntu enable service ssh and start it
  ansible.builtin.service:
    name: ssh
    enabled: yes
    state: started
  when: ansible_facts['distribution'] == 'Ubuntu'
