---
- hosts: localhost
  tasks:
    - name: "Kali WSL Install Packages"
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # 1 day
        name:
          - kali-desktop-core
          - exiftool
          - gcc
          - geeqie
          - man-db
          - restic
          - stow
          - 7zip
          - unzip
          - usbutils
        state: present
      when: ansible_distribution == 'Kali' and ansible_virtualization_type == 'wsl'
    - name: "Kali WSL Uninstall Packages"
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # 1 day
        name:
          - neovim
        state: absent
      when: ansible_distribution == 'Kali' and ansible_virtualization_type == 'wsl'
