---
- hosts: localhost
  tasks:
#    - name: Debug facts
#      ansible.builtin.debug:
#        msg: "distro={{ ansible_facts['distribution'] }} virt={{ ansible_facts['virtualization_type'] }}"
    - name: "Kali WSL Install Packages"
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # 1 day
        name:
          - kali-desktop-core
          - exiftool
          - gcc
          - geeqie
          - man-db
          - restic
          - stow
          - 7zip
          - unzip
          - usbutils
        state: present
      when: ansible_facts['distribution'] == 'Kali' and ansible_facts['virtualization_type'] in ['wsl', 'container']
    - name: "Kali WSL Uninstall Packages"
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # 1 day
        name:
          - neovim
        state: absent
      when: ansible_facts['distribution'] == 'Kali' and ansible_facts['virtualization_type'] in ['wsl', 'container']
